# Generated by Django 5.0.7 on 2024-07-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
