# Generated by Django 5.0.7 on 2024-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsendApp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('proposed', 'Proposed'), ('client_accepted', 'Client Accepted'), ('client_declined', 'Client Declined')], default='posted', max_length=50),
        ),
    ]
