# Generated by Django 5.0.7 on 2024-07-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsendApp', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('runner', 'Runner')], default='client', max_length=10),
        ),
    ]
