# Generated by Django 5.0.7 on 2024-07-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsendApp', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('runner', 'Runner')], max_length=10, null=True),
        ),
    ]
