# Generated by Django 5.0.7 on 2024-08-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsendApp', '0010_remove_profile_latitude_remove_profile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('proposed', 'Proposed'), ('client_accepted', 'Client Accepted'), ('client_declined', 'Client Declined'), ('paid', 'Paid')], default='posted', max_length=50),
        ),
    ]
