# Generated by Django 5.0.7 on 2024-08-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsendApp', '0011_profile_latitude_profile_longitude_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('runner', 'Runner')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
