# Generated by Django 5.0.7 on 2024-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsendApp', '0013_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
